package interfaces;

import codes.DBconnect;
import static interfaces.studentReg.validateID;
import static interfaces.studentReg.validateTele;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Arrays;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class staffReg extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    int timeRun=0;
    /**
     * Creates new form staffReg
     */
    public staffReg() {
        initComponents();
        
        con=DBconnect.connect();
        
        groupButton();
        //hide validation fields
        Rname.setVisible(false);Rnic.setVisible(false);Radrs.setVisible(false);
        Rnum.setVisible(false);Rmail.setVisible(false);Runame.setVisible(false);Rpwd.setVisible(false);Rpwd2.setVisible(false);
        
        //set the form center in the window
        setLocationRelativeTo(null);
        
        currentDate();
        
        
        //Time Setting done here
        new Thread()
        {
        public void run()
        {
        while(timeRun==0)
        {
            Calendar cal=new GregorianCalendar();
            
            int hour=cal.get(Calendar.HOUR);
            int minute=cal.get(Calendar.MINUTE);
            int second=cal.get(Calendar.SECOND);
            int AM_PM=cal.get(Calendar.AM_PM);
            String day_night=" ";
            
            if(AM_PM==1)
        {
            day_night="PM";
        }
            else
        {
            day_night="AM";
        }
            
            String time= hour+":"+minute+":"+second+" "+day_night;
            showtime.setText(time);
        }
        }
        
        }.start();  
            
       //Time setting ends here
    }

   
    
    //show date
    public void currentDate(){

                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    showdate.setText(year+"-"+(month+1)+"-"+day);
                    
               }
    
    private void groupButton() {

    ButtonGroup bg1 = new ButtonGroup( );

    bg1.add(mm);
    bg1.add(ff);

}
    
    //validate telephone number
     public static boolean validateTele(String tele){
        boolean status=false;
        String tele_PATTERN="^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]";
        Pattern pattern=Pattern.compile(tele_PATTERN);
        Matcher matcher=pattern.matcher(tele);
        if(matcher.matches()){
            status=true;
        }
        else{
            status=false;
        }
        return status;
    }
    
     //validate nic
    public static boolean validateID(String ID){
        boolean status=false;
        String ID_Pattern="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][v/V]";
        Pattern pattern=Pattern.compile(ID_Pattern);
        Matcher matcher=pattern.matcher(ID);
        if(matcher.matches()){
            status=true;
        }
        else{
            status=false;
        }
        return status;
    }
    //validate email
   public static boolean validateEmail(String email){
        boolean status =false;
        String EMAIL_PATTERN="^[_A-Za-z0-9-]*@"+"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        Pattern pattern=Pattern.compile(EMAIL_PATTERN);
        Matcher matcher=pattern.matcher(email);
        if(matcher.matches()){
           status=true; 
        }
        else{
            status=false;
        }
        return status;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        showdate = new javax.swing.JLabel();
        showtime = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        maill = new javax.swing.JTextField();
        numm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        add = new javax.swing.JTextArea();
        mm = new javax.swing.JRadioButton();
        ff = new javax.swing.JRadioButton();
        nicc = new javax.swing.JTextField();
        nmm = new javax.swing.JTextField();
        idd = new javax.swing.JTextField();
        Rname = new javax.swing.JLabel();
        Rnic = new javax.swing.JLabel();
        Radrs = new javax.swing.JLabel();
        Rnum = new javax.swing.JLabel();
        Rmail = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Rpwd2 = new javax.swing.JLabel();
        pwdd2 = new javax.swing.JPasswordField();
        Rpwd = new javax.swing.JLabel();
        pwdd = new javax.swing.JPasswordField();
        Runame = new javax.swing.JLabel();
        unmm = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        poss = new javax.swing.JComboBox();
        lo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 695));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 280, 100);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Welcome to LIBERO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 50, 480, 50);

        showdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showdate.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(showdate);
        showdate.setBounds(830, 30, 90, 20);

        showtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showtime.setForeground(new java.awt.Color(0, 51, 102));
        showtime.setText(" ");
        getContentPane().add(showtime);
        showtime.setBounds(830, 50, 90, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reg2.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(690, 390, 240, 280);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reg1.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(580, 350, 260, 260);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Employee ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 140, 110, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Position");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 240, 130, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("NIC");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 290, 70, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Gender");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 340, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 400, 80, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Contact number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 510, 140, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 570, 100, 20);
        getContentPane().add(maill);
        maill.setBounds(230, 560, 190, 30);

        numm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nummKeyTyped(evt);
            }
        });
        getContentPane().add(numm);
        numm.setBounds(230, 510, 190, 30);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(164, 94));

        add.setColumns(20);
        add.setRows(5);
        jScrollPane1.setViewportView(add);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 390, 260, 100);

        mm.setBackground(new java.awt.Color(255, 255, 255));
        mm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mm.setText("Male");
        mm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmActionPerformed(evt);
            }
        });
        getContentPane().add(mm);
        mm.setBounds(230, 340, 80, 30);

        ff.setBackground(new java.awt.Color(255, 255, 255));
        ff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ff.setText("Female");
        getContentPane().add(ff);
        ff.setBounds(330, 340, 80, 30);

        nicc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                niccKeyReleased(evt);
            }
        });
        getContentPane().add(nicc);
        nicc.setBounds(230, 290, 180, 30);

        nmm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmmKeyReleased(evt);
            }
        });
        getContentPane().add(nmm);
        nmm.setBounds(230, 190, 180, 30);

        idd.setBackground(new java.awt.Color(204, 204, 255));
        idd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                iddKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                iddKeyTyped(evt);
            }
        });
        getContentPane().add(idd);
        idd.setBounds(230, 140, 90, 30);

        Rname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rname.setForeground(new java.awt.Color(255, 0, 0));
        Rname.setText("*Required");
        getContentPane().add(Rname);
        Rname.setBounds(420, 210, 70, 20);

        Rnic.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rnic.setForeground(new java.awt.Color(255, 0, 0));
        Rnic.setText("*Required");
        getContentPane().add(Rnic);
        Rnic.setBounds(420, 310, 70, 20);

        Radrs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Radrs.setForeground(new java.awt.Color(255, 0, 0));
        Radrs.setText("*Required");
        getContentPane().add(Radrs);
        Radrs.setBounds(500, 470, 70, 20);

        Rnum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rnum.setForeground(new java.awt.Color(255, 0, 0));
        Rnum.setText("*Required");
        getContentPane().add(Rnum);
        Rnum.setBounds(430, 530, 70, 20);

        Rmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rmail.setForeground(new java.awt.Color(255, 0, 0));
        Rmail.setText("*Required");
        getContentPane().add(Rmail);
        Rmail.setBounds(430, 580, 70, 20);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("REGISTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 310, 110, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Username");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 130, 100, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("Password");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(570, 190, 100, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setText("Confirm password");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(570, 250, 150, 20);

        Rpwd2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rpwd2.setForeground(new java.awt.Color(255, 0, 0));
        Rpwd2.setText("*Required");
        getContentPane().add(Rpwd2);
        Rpwd2.setBounds(860, 280, 70, 20);
        getContentPane().add(pwdd2);
        pwdd2.setBounds(740, 250, 170, 30);

        Rpwd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Rpwd.setForeground(new java.awt.Color(255, 0, 0));
        Rpwd.setText("*Required");
        getContentPane().add(Rpwd);
        Rpwd.setBounds(860, 220, 70, 20);
        getContentPane().add(pwdd);
        pwdd.setBounds(740, 190, 170, 30);

        Runame.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Runame.setForeground(new java.awt.Color(255, 0, 0));
        Runame.setText("*Required");
        getContentPane().add(Runame);
        Runame.setBounds(860, 160, 70, 20);
        getContentPane().add(unmm);
        unmm.setBounds(740, 130, 170, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("Employee name");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 190, 130, 20);

        poss.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        poss.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Librarian", "Admin" }));
        getContentPane().add(poss);
        poss.setBounds(230, 240, 140, 30);

        lo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lo.setForeground(new java.awt.Color(0, 51, 102));
        lo.setText("login");
        lo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loMouseClicked(evt);
            }
        });
        getContentPane().add(lo);
        lo.setBounds(830, 10, 90, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkground.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 686);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nummKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nummKeyTyped

    }//GEN-LAST:event_nummKeyTyped

    private void mmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mmActionPerformed

    private void niccKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_niccKeyReleased

    }//GEN-LAST:event_niccKeyReleased

    private void nmmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmmKeyReleased

    }//GEN-LAST:event_nmmKeyReleased

    private void iddKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iddKeyReleased

    }//GEN-LAST:event_iddKeyReleased

    private void iddKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_iddKeyTyped

    }//GEN-LAST:event_iddKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                //hide validation fields
        Rname.setVisible(false);Rnic.setVisible(false);Radrs.setVisible(false);
        Rnum.setVisible(false);Rmail.setVisible(false);Runame.setVisible(false);Rpwd.setVisible(false);Rpwd2.setVisible(false);
        
           boolean requiredField=true;
           
           //confirm pwd
     
           if(Arrays.equals(pwdd.getPassword(), pwdd2.getPassword()))
            {
                   JOptionPane.showMessageDialog(this, "Passwords are matched");
             }
           else{
            JOptionPane.showMessageDialog(this, "Passwords are not matched");
            requiredField = false;
           }
        
        //validating fields
        if(nmm.getText().length()==0||nicc.getText().length()==0||add.getText().length()==0||numm.getText().length()==0||maill.getText().length()==0||unmm.getText().length()==0||pwdd.getText().length()==0||pwdd2.getText().length()==0)
        {
            requiredField=false;
        }
        //validate telephone number
        if(validateTele(numm.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid telephone number");
            Rnum.setVisible(true);
            requiredField=false;
        }
        
        //validate nic 
        if(validateID(nicc.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid nic number");
            Rnic.setVisible(true);
            requiredField=false;
        }
        
        //validate email 
        if(validateEmail(maill.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid email");
            Rmail.setVisible(true);
            requiredField=false;
        }
        
        //add records
        if(requiredField==true)
        {
            //succesfull adding
     
        String gen=" ";
            if (mm.isSelected()) {
                gen="Male";
            }
            else{
                gen="Female";
            }
        String ii=idd.getText();
        String nm=nmm.getText();
        String pos=poss.getSelectedItem().toString();
        String nic=nicc.getText();
        String ad=add.getText();
        String num=numm.getText();
        String mail=maill.getText();
        String unm=unmm.getText();
        String pwd2=pwdd2.getText();
        
        try {
            String q="INSERT INTO staff (EmployeeID,EmployeeName,Position,NIC,Gender,Address,ContactNumber,Email,Username,ConfirmPassword) VALUES ('"+ ii +"','"+ nm +"','"+ pos +"','"+ nic +"','"+ gen +"','"+ ad +"','"+ num +"','"+ mail +"','"+ unm +"','"+ pwd2 +"')";
            pst=con.prepareStatement(q);
            pst.execute();
            
            //clear all textboxes after deleting
            nmm.setText(" ");nicc.setText(" ");add.setText(" ");numm.setText(" ");maill.setText(" ");unmm.setText(" ");pwdd.setText(" ");pwdd2.setText(" ");
            Random rand = new Random();
            int selected = 100000+rand.nextInt(200000);
            idd.setText(String.valueOf(selected));
            
            login log=new login();
            log.setVisible(true);
            this.dispose();
           // JOptionPane.showMessageDialog(this, "Registered Successfully");
            
        } catch (Exception e) {
            System.out.println(e);
        }
        }
        else
        {
            //display appropriate error (*required)
            if(nmm.getText().length()==0){Rname.setVisible(true);}
            if(nicc.getText().length()==0){Rnic.setVisible(true);}
            if(add.getText().length()==0){Radrs.setVisible(true);}
            if(numm.getText().length()==0){Rnum.setVisible(true);}
            if(maill.getText().length()==0){Rmail.setVisible(true);}
            if(unmm.getText().length()==0){Runame.setVisible(true);}
            if(pwdd.getText().length()==0){Rpwd.setVisible(true);}
            if(pwdd2.getText().length()==0){Rpwd2.setVisible(true);}
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Random rand = new Random();
        int selected = 100000+rand.nextInt(200000);
        idd.setText(String.valueOf(selected));
    }//GEN-LAST:event_formWindowOpened

    private void loMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loMouseClicked
        login log=new login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Radrs;
    private javax.swing.JLabel Rmail;
    private javax.swing.JLabel Rname;
    private javax.swing.JLabel Rnic;
    private javax.swing.JLabel Rnum;
    private javax.swing.JLabel Rpwd;
    private javax.swing.JLabel Rpwd2;
    private javax.swing.JLabel Runame;
    private javax.swing.JTextArea add;
    private javax.swing.JRadioButton ff;
    private javax.swing.JTextField idd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lo;
    private javax.swing.JTextField maill;
    private javax.swing.JRadioButton mm;
    private javax.swing.JTextField nicc;
    private javax.swing.JTextField nmm;
    private javax.swing.JTextField numm;
    private javax.swing.JComboBox poss;
    private javax.swing.JPasswordField pwdd;
    private javax.swing.JPasswordField pwdd2;
    private javax.swing.JLabel showdate;
    private javax.swing.JLabel showtime;
    private javax.swing.JTextField unmm;
    // End of variables declaration//GEN-END:variables
}
