package interfaces;

import codes.DBconnect;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import net.proteanit.sql.DbUtils;

public class studentReg extends javax.swing.JFrame {
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    int timeRun=0;
    
    public studentReg() {
        initComponents();
        
        con=DBconnect.connect();
        
        tableload();
        
        //hide validation fields
        jLabel17.setVisible(false);
        jLabel18.setVisible(false);jLabel19.setVisible(false);
        jLabel20.setVisible(false);jLabel21.setVisible(false);
        
        //set the form center in the window
        setLocationRelativeTo(null);
        
        //set table transparancy
        jTable1.setOpaque(false);
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class)).setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jTable1.setShowGrid(false);
        
        currentDate();
        
        new Thread()
        {
        public void run()
        {
        while(timeRun==0)
        {
            Calendar cal=new GregorianCalendar();
            
            int hour=cal.get(Calendar.HOUR);
            int minute=cal.get(Calendar.MINUTE);
            int second=cal.get(Calendar.SECOND);
            int AM_PM=cal.get(Calendar.AM_PM);
            String day_night=" ";
            
            if(AM_PM==1)
        {
            day_night="PM";
        }
            else
        {
            day_night="AM";
        }
            
            String time= hour+":"+minute+":"+second+" "+day_night;
            showtime.setText(time);
        }
        }
        
        }.start();  
            
       //Time setting ends here
    }
    
    //show date
    public void currentDate(){

                    Calendar cal=new GregorianCalendar();
                    int month=cal.get(Calendar.MONTH);
                    int year=cal.get(Calendar.YEAR);
                    int day=cal.get(Calendar.DAY_OF_MONTH);
                    showdate.setText(year+"-"+(month+1)+"-"+day);
               }
    
    //loard the record to table after adding  
    public void tableload(){
        try {
            String sql="select MemberID,MemberType,MemberName,NIC,Address,ContactNumber from student";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
    }
    
    //validate telephone number
     public static boolean validateTele(String tele){
        boolean status=false;
        String tele_PATTERN="^[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]";
        Pattern pattern=Pattern.compile(tele_PATTERN);
        Matcher matcher=pattern.matcher(tele);
        if(matcher.matches()){
            status=true;
        }
        else{
            status=false;
        }
        return status;
    }
    
     //validate nic
    public static boolean validateID(String ID){
        boolean status=false;
        String ID_Pattern="[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][v/V]";
        Pattern pattern=Pattern.compile(ID_Pattern);
        Matcher matcher=pattern.matcher(ID);
        if(matcher.matches()){
            status=true;
        }
        else{
            status=false;
        }
        return status;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        showdate = new javax.swing.JLabel();
        showtime = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        num = new javax.swing.JTextField();
        adrs = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        nm = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        acd = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 695));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Member Registration");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 50, 490, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 280, 100);

        showdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showdate.setForeground(new java.awt.Color(0, 51, 102));
        getContentPane().add(showdate);
        showdate.setBounds(790, 10, 140, 20);

        showtime.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showtime.setForeground(new java.awt.Color(0, 51, 102));
        showtime.setText(" ");
        getContentPane().add(showtime);
        showtime.setBounds(790, 30, 100, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userr.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(740, 50, 190, 220);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 153));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(590, 410, 170, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 153));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 360, 170, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 153));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 310, 170, 30);

        num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numActionPerformed(evt);
            }
        });
        num.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numKeyTyped(evt);
            }
        });
        getContentPane().add(num);
        num.setBounds(230, 410, 190, 30);

        adrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adrsActionPerformed(evt);
            }
        });
        getContentPane().add(adrs);
        adrs.setBounds(230, 360, 190, 30);

        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicKeyReleased(evt);
            }
        });
        getContentPane().add(nic);
        nic.setBounds(230, 310, 190, 30);

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(230, 160, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Member ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 100, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setText("Member type");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(60, 210, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("NIC");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 310, 70, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 360, 80, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Contact number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 410, 140, 22);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/homeButton.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(860, 580, 75, 70);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setForeground(new java.awt.Color(204, 204, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setForeground(new java.awt.Color(51, 51, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Member ID", "Member type", "Member name", "NIC", "Address", "Contact number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRequestFocusEnabled(false);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 490, 830, 150);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*Required");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(430, 430, 70, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*Required");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(430, 180, 70, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*Required");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(430, 380, 70, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*Required");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(430, 280, 70, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*Required");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(430, 330, 70, 20);

        nm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nmKeyReleased(evt);
            }
        });
        getContentPane().add(nm);
        nm.setBounds(230, 260, 190, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 153));
        jLabel22.setText("Member name");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(60, 260, 120, 20);

        acd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        acd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Academic", "Student" }));
        getContentPane().add(acd);
        acd.setBounds(230, 210, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bkground.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //hide validation fields
        jLabel17.setVisible(false);jLabel18.setVisible(false);jLabel19.setVisible(false);
        jLabel20.setVisible(false);jLabel21.setVisible(false);
        
        boolean requiredField=true;
        //validating fields
        if(id.getText().length()==0||nic.getText().length()==0||nm.getText().length()==0||adrs.getText().length()==0||num.getText().length()==0)
        {
            requiredField=false;
        }
        //validate telephone number
        if(validateTele(num.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid telephone number");
            jLabel17.setVisible(true);
            requiredField=false;
        }
        
        //validate nic 
        if(validateID(nic.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid nic number");
            jLabel21.setVisible(true);
            requiredField=false;
        }
        
        //add records
        if(requiredField==true)
        {
            //succesfull adding
        String id1=id.getText();
        String ac=acd.getSelectedItem().toString();
        String nm1=nm.getText();
        String nic1=nic.getText();
        String adrs1=adrs.getText();
        String num1=num.getText();
        
        
        try {
            String q="INSERT INTO student (MemberID,MemberType,MemberName,NIC,Address,ContactNumber) VALUES ('"+ id1 +"','"+ ac +"','"+ nm1 +"','"+ nic1 +"','"+ adrs1 +"','"+ num1 +"')";
            pst=con.prepareStatement(q);
            pst.execute();
            tableload();
            //clear all textboxes after deleting
            id.setText("");nic.setText("");nm.setText("");num.setText("");adrs.setText("");
            
            JOptionPane.showMessageDialog(this, "Added Successfully");
        } catch (Exception e) {
            System.out.println(e);
        }
        }
        else
        {
            //display appropriate error (*required)
            if(id.getText().length()==0){jLabel18.setVisible(true);}
            if(nic.getText().length()==0){jLabel21.setVisible(true);}
            if(nm.getText().length()==0){jLabel20.setVisible(true);}
            if(adrs.getText().length()==0){jLabel19.setVisible(true);}
            if(num.getText().length()==0){jLabel17.setVisible(true);}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //hide validation fields
        jLabel17.setVisible(false);jLabel18.setVisible(false);jLabel19.setVisible(false);
        jLabel20.setVisible(false);jLabel21.setVisible(false);
        
        boolean requiredField=true;
        //validating fields
        if(id.getText().length()==0||nic.getText().length()==0||nm.getText().length()==0||adrs.getText().length()==0||num.getText().length()==0)
        {
            requiredField=false;
        }
        //validate telephone number
        if(validateTele(num.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid telephone number");
            jLabel17.setVisible(true);
            requiredField=false;
        }
        
        //validate nic 
        if(validateID(nic.getText())==false)
        {
            JOptionPane.showMessageDialog(this, "Insert a valid nic number");
            jLabel21.setVisible(true);
            requiredField=false;
        }

        //update records
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to update??");
        if(requiredField==true){
        if (x==0) {
            String id1=id.getText();
            String ac=acd.getSelectedItem().toString();
            String nm1=nm.getText();
            String nic1=nic.getText();
            String adrs1=adrs.getText();
            String num1=num.getText();
            
            
            String sql="update student set MemberName='"+ nm1 +"',NIC='"+ nic1 +"',Address='"+ adrs1 +"',ContactNumber='"+ num1 +"' where MemberID='"+ id1+"'";
            try {
            pst=con.prepareStatement(sql);
            pst.execute();
            tableload();
            //clear all textboxes after deleting
            id.setText("");nic.setText("");nm.setText("");num.setText("");adrs.setText("");
            
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            } catch (Exception e) {
            }
        }
        }
        else
        {
            //display appropriate error (*required)
            if(id.getText().length()==0){jLabel18.setVisible(true);}
            if(nic.getText().length()==0){jLabel21.setVisible(true);}
            if(nm.getText().length()==0){jLabel20.setVisible(true);}
            if(adrs.getText().length()==0){jLabel19.setVisible(true);}
            if(num.getText().length()==0){jLabel17.setVisible(true);}
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        
    }//GEN-LAST:event_idKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //delete records
        int x=JOptionPane.showConfirmDialog(null, "Do you really want to delete??");
        
        if (x==0) {
            String i=id.getText();
            String sql="delete from student where MemberID='"+ i +"'";
            try {
                
            pst=con.prepareStatement(sql);
            pst.execute();
            tableload();
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
            //clear all textboxes after deleting
            id.setText("");nic.setText("");nm.setText("");num.setText("");adrs.setText("");
            
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //filling the fileds when select the row 
        int r=jTable1.getSelectedRow();
        String i1=jTable1.getValueAt(r, 0).toString();
        String ty=jTable1.getValueAt(r, 1).toString();
        String n1=jTable1.getValueAt(r, 2).toString();
        String ni1=jTable1.getValueAt(r, 3).toString();
        String a1=jTable1.getValueAt(r, 4).toString();
        String num1=jTable1.getValueAt(r, 5).toString();
        
        
        id.setText(i1);
        acd.setSelectedItem(ty);
        nm.setText(n1);
        nic.setText(ni1);
        adrs.setText(a1);
        num.setText(num1);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
             //search for student by id
        String id1=id.getText();
        
        String sql="select MemberID,MemberType,MemberName,NIC,Address,ContactNumber from student where MemberID like '%"+ id1 +"%'";
        try {
                
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         
            } catch (Exception e) {
            }
    }//GEN-LAST:event_idKeyReleased

    private void nicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyReleased
         //search for student by nic
        String nicl=nic.getText();
        
        String sql="select MemberID,MemberType,MemberName,NIC,Address,ContactNumber from student where NIC like '%"+ nicl +"%'";
        try {
                
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
         
            } catch (Exception e) {
            }
    }//GEN-LAST:event_nicKeyReleased

    private void numKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numKeyTyped
        // only accept numerical values here
        char c= evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE) || c== KeyEvent.VK_DELETE)){
            evt.consume();}
    }//GEN-LAST:event_numKeyTyped

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        librarianHome hom=new librarianHome();
         hom.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void nmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nmKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nmKeyReleased

    private void numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numActionPerformed

    private void adrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adrsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adrsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox acd;
    private javax.swing.JTextField adrs;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nic;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField num;
    private javax.swing.JLabel showdate;
    private javax.swing.JLabel showtime;
    // End of variables declaration//GEN-END:variables
}
